### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Result on my actions: https://github.com/MatthijsBurgh/openpose/actions/runs/449344457

The CUDA jobs fails because of an issue with GCC 5.5, https://github.com/NVIDIA/apex/issues/529. GH Actions doesn't support GCC 5.4. And CUDA doesn't support newer than GCC 5.X. So I don't have a solution for these jobs.

This might not be the cleanest PR. I suggest to cleanup the scripts further so that are generic scripts, CI scripts, Travis scripts and GH action scripts, etc. And that all TRAVIS/GH Action variables are only use in their specific scripts and generic variables in the other scripts.

Because of the failing jobs, I haven't been able to test the docs generation. I don't know if the DOCS could be generated after another job.

P.S. Setup a branch protection and require these jobs to succeed. I have seen the TRAVIS job history getting worse over time. This shouldn't happen.

Solves #1809

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Maintainers should enable actions

**Comment by MatthijsBurgh** [comment]
@gineshidalgo99 ping;)

**Comment by gineshidalgo99** [comment]
Hi @MatthijsBurgh ,

Thanks a lot for this! I'll be very happy to merge your changes! However, you have modified a lot of files that are being used in many different kind of software, hardware, and operating systems (eg install_deps_and_cuda.sh, install_deps.sh, etc), so I am very concerned with backwards compatibility.

I could do either of the following 2 things:
- Either cherry pick your changes and add the subset that enables actions, without modifying anything else that might affect backwards compatibility. Cons: Those changes would appear as my own commits and your name wouldn't appear on them, which would be unfair!
- Or please, make a 2nd PR with the very minimal changes that enables GitHub actions without affecting other scripts. You are free to duplicate files (eg install_deps_and_cuda.sh if "bash" really did not work with GitHub actions and it really required "source"). I will later in future commits try to clean up duplication, but duplication is highly preferable over modifying very old files!

Let me know which one you prefer, Im open to both! :)

**Comment by MatthijsBurgh** [comment]
The backwards compatibility shouldn't be broken. `install_cudnn.sh` was actually broken. Because it didn't have the ubuntu version available.

I switched from bash to source to have the CI env variable available to limit verbosity of `wget`, which was polluting the logs. Another solution would be to  add `export CI` somewhere. Do you prefer that?

`install_deps.sh` has changed more significant. All python changes are related to `numpy` and `opencv` not supporting python2 anymore in their newest releases. Plus `opencv` could not be found if it was installed in system dir. Therefore I install it in user in CI, but still in system dir on people their pc.
Also I make sure pip is updated. Older versions sometimes can't install newer packages.
Other changes in that file are only reducing verbosity of apt-get.

I hope this explanation provides you enough clarity to keep these changes. I would like to hear your preference about the source/bash.

**Comment by gineshidalgo99** [comment]
_I switched from bash to source to have the CI env variable available to limit verbosity of wget, which was polluting the logs. Another solution would be to add export CI somewhere. Do you prefer that?_
I want to minimize changes to files already being in used. These files are also mentioned in the doc and provided to the users to install the OpenPose prerequisites, so they should not change in behavior. I do not mind that the logs are polluted as much as I do making the minimal changes. About the logs being polluted, not sure the pros/cons of export CI, but I am ok checking a log that has a long wget message, it is not a critical issue I believe, unless there is a problem associated with it?

About the rest, I still see many changes here that are not clear to me why they are happening. `If` statements with the `; then` broken into a new line, `--assume-yes replaced` by `-yq`, some apt-get install requirements changed, etc. As I said, these scripts are and have been used for a few years and in multiple operating systems, so I can't make changes to those files unless there is a enhancement / bug fix / speed improvement / clear benefit of any way related to those changes.

As I said, I can cherry pick some of your changes, but if you want to get the proper recognition for the changes and also so we can discuss each one individually, I'd need a PR for each individual case. This PR is too big, eg any bugs resulting from it would be very hard to track, not in GitHub actions, but in other operating systems or hardware based on these scripts. Eg
1. The first PR should "just" fix each current typos/bug in the current code (a few bugs/typos can be combined in a single PR too). E.g., install_cudnn.sh to actually fix the bug it currently has not checking OS (but without all the other wget changes).
2. Another one with the very minimal changes to enable GitHub actions
3. And then you can do any other PR for any other reason or enhancement you want to discuss. Eg replacing assume-yes for yq if there is a valid reason for that, etc.

That way I can combine each one of your PRs or discuss them in further details! There is just many changes here! Let me know your thoughts, I could always cherry pick some your changes if you are not interested on this!

**Comment by MatthijsBurgh** [comment]
I understand and agree that spitting this PR is needed. I will start with adding the GitHub actions (not removing travis yet). We can work from there. I will try to prevent any unneeded style changes.

P.S. The verbosity of `wget` should be reduced. As in [this log](https://travis-ci.org/github/CMU-Perceptual-Computing-Lab/openpose/jobs/754006360) 37375 lines of the total 40151 lines is `wget`  updating is status. This is inacceptable.

**Comment by MatthijsBurgh** [comment]
@gineshidalgo99 could you please enable actions on this repo?

**Comment by gineshidalgo99** [comment]
Thanks again for this amazing PR (and for splitting it in parts!). I have just made a final push that fixes the CUDA issue (by compiling it in Ubuntu 18 and 20), so now all tests pass are everything is green again. I'll be replacing the Travis icons in the README.md for their GitHub actions equivalents, but other than that it is finished!

**Comment by gineshidalgo99** [comment]
In addition, and as part of my thank you, I have added you to the list of external "Contributors", given that this was a considerably big set of PRs. You can let me know if you want me to remove you from there (or modify any information I added in there).
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/contributors.md

**Comment by MatthijsBurgh** [comment]
@gineshidalgo99 thank you for adding me to the contributors.

I saw that the docs generation succeeded (without testing ;) ). I wanted to know if this only succeeded, but also produced correct pages. Though I can't find the link to where the documentation is hosted.
Is it just me? Otherwise it might be good to place a link at a more prominent place.

**Comment by gineshidalgo99** [comment]
It is in here:
https://cmu-perceptual-computing-lab.github.io/openpose/

That you can find in https://github.com/CMU-Perceptual-Computing-Lab/openpose --> to the right in the "Environments" section --> and clicking on "github-pages"

And yes, I have to put the link in a more prominent place. But before that, there are quite a few bugs in that page (missing images, wrong table, etc). I have to figure out how to solve those issues before making the link more public

**Comment by MatthijsBurgh** [comment]
Screenshot from 2021-01-20 08-59-54
This is what I see, under contributors there is only the language section.

I see that indeed the images are missing.

**Comment by gineshidalgo99** [comment]
It seems that the "Environments" section only appears on a GitHub page for the admins of that page. I did not know that :)

After a few hours, I finally got all the images and tables working, as well as all the docs showing (not only the README.md) and sorted out in a logical way.
https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/

This page is now mentioned in the README.md, doc/README.md, and in the top-right side of the main page (in the "About" section).

I believe this solves all the issues? I still have a few minor issues to solve with hyperlinks (eg from the doc to the actual examples code or in between the same document), but that should be about it.

**Comment by MatthijsBurgh** [comment]
@gineshidalgo99 That is a huge improvement. I am proud to see the results of our combined efforts.

**Comment by gineshidalgo99** [comment]
Yes it is. Thanks for bothering me about the GH pages and thanks for all the PRs, they really enabled this!!

I have made a last commit that fixes the few minor errors I knew about. In theory everything is now 100% functional and I actually recommend in the doc to follow the Doxygen version rather than the *.md files.

Feel free to let me know about any new potential extensions, bugs, etc. (or any PR tackling them!)

**Pull request closed without merging**
