### PR TITLE
Adding Dockerfiles

### PR DESCRIPTION
**Pull request by ruffsl**
I'd like to suggest providing users working Dockerfiles to easily build and run OpenPose.
Here is a start of the docker files and run scripts that are working for me.
To test this, in addition to [docker](https://www.docker.com/), you'll also need [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) installed.
``` terminal
$ cd openpose/docker
$ make build
$ ./gpu/run.sh
```
I've added some suggestions such as building directly `FROM bvlc/caffe:gpu`, and following some build conventions. I first tried using bvlc/caffe:gpu and everything, but encountered some linking issues, so resorted to using the current build structure just to get this out early.

This is a follow up for https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/11

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Thank you so much! I will take a look within 2-4 weeks and add it if everything is good! So you can keep improving it if you wish because I will definitively add it!

**Comment by ruffsl** [comment]
An brief attempt was made to build using cmake [here](https://github.com/ruffsl/openpose/commit/e7e448e3f1676c9c1ce7fc7824ff2885bbed315a), but stoped short when ecountering cflag issues.
I'm afraid I'm out of my depth in using all of new cmake files pushed to another [public fork](https://github.com/bakjos/openpose/network).
Perhaps @bakjos could shed shed some light on how to integrate his repo.

**Comment by mjsobrep** [comment]
If anyone is interested, I had played around a little bit with this a while back as well and documented my efforts here: http://michaelsobrepera.com/guides/openposeaws.html Although it looks like Ruffin has it working pretty well...

**Comment by bhack** [comment]
What is missing here? @bryant1410 can we unify the effort of https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/88 in this?

**Comment by bryant1410** [comment]
What about adding a dockerignore for the .git folder?

**Comment by burningion** [comment]
Just wanted to leave an update for anyone else who stumbles onto this thread, looking for a Dockerized version of OpenPose.

This branch still works, the only change you'll need to do is replace `make build` with either `make build_gpu` or `make `build_cpu`, depending on your installation. 

Of course, the GPU version requires [NVDIA's Docker version](https://github.com/NVIDIA/nvidia-docker), as stated above. Following those instructions worked for me, and gave a good starting point for development.

For performance reference, on a GTX 980ti, I got around 7 fps with the included code.

**Comment by nanthakumar94** [comment]
Hi you explain how to run this openpose in windows 10 because i install all requirements tool get the all files one file is missing openposedemo.exe file

**Comment by moiseevigor** [comment]
Hi, just want to share the simple `Dockerfile`, that produces working image with [OpenPose 1.4.0, OpenCV, CUDA 8, CuDNN 6 and Python2.7](https://gist.github.com/moiseevigor/11c02c694fc0c22fccd59521793aeaa6). It uses the latest Caffe build through the `bvlc/caffe:gpu` image.

**Comment by archenroot** [comment]
another latest Docker file: docker pull gemfield/openpose

**Comment by gineshidalgo99** [comment]
Given all the conflicts and how old it is, closed.

Note that there is a new version in #1102

Thanks!

**Pull request closed without merging**
