### PR TITLE
Fix paths of Boost libraries in Windows

### PR DESCRIPTION
**Pull request by thomasfaingnaert**
The precompiled boost libraries in http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/caffe3rdparty_15_2019_03_14.zip do not have a `lib` prefix in their filenames. As a consequence, CMake fails to find them. This PR simply removes this `lib` prefix from CMakeLists.txt.

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
That Cmake code that you modified is applied ONLY for CPU and CL versions. However, the zip http://posefs1.perception.cs.cmu.edu/OpenPose/3rdparty/windows/caffe3rdparty_15_2019_03_14.zip is ONLY applied for CUDA version. So there is no relation between them. I would say if you are facing that error, it is coming from something else.

**Comment by thomasfaingnaert** [comment]
I am building the CPU version. So somehow the wrong zip is downloaded then?

**Comment by thomasfaingnaert** [comment]
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/e7632893c28495f0a4af788d9c55c720be63ff2a/CMakeLists.txt#L506

This would indicate that this zip is downloaded regardless of GPU mode, no?

**Comment by gineshidalgo99** [comment]
You are right! My bad! (Sorry, the CPU author is not me so I got confused).

Then, as a last question before accepting your PR, if you change that path, does the CPU version works in your machine currently?

**Comment by thomasfaingnaert** [comment]
Compilation works perfectly, though an additional issue I had was that the examples do not run as-is.
The reason is that the WrapperStruct's RenderMode is GPU by default, so I had to add this snippet to every example:
```cpp
op::WrapperStructPose wrapperStructPose{};
wrapperStructPose.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructPose);

op::WrapperStructFace wrapperStructFace{};
wrapperStructFace.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructFace);

op::WrapperStructHand wrapperStructHand{};
wrapperStructHand.renderMode = op::RenderMode::Cpu;
opWrapper.configure(wrapperStructHand);
```
Perhaps it would be better to set this to Cpu if OpenPose is compiled in CPU mode? If so, I will create another PR for this.

**Comment by gineshidalgo99** [comment]
Great thanks! Merged.

Now, about your second issue. By default, OpenPose is supposed to automatically detect it (at least in the C++ demo and C++ examples). Maybe I skipped it somewhere, could you let me know where did that happen? Thanks!

**Pull request merged**
