### PR TITLE
Add support for Nvidia NVCaffe

### PR DESCRIPTION
**Pull request by HBadertscher**
Hi,

This pull request fixes issue #1002 by adding a new CMake flag `NV_CAFFE` and `#ifdef` where needed to distinguish between the standard Caffe and NVCaffe.

This has been tested with the official Nvidia Docker image [`nvcr.io/nvidia/caffe:18.12-py2`](https://ngc.nvidia.com/catalog/containers/nvidia:caffe).

Do you think it would be possible to test this automatically using Travis too?

I'm happy about any feedback.

cc @chrigima

### CODE REVIEW

**Comment by soulslicer** [comment]
Does Nvidia host NVCAFFE on github somewhere?

**Comment by soulslicer** [comment]
I tried to compile your code and link it agains the official NVCAFFE. I ran across this error though.

`/home/user/nvcaffe/include/caffe/util/float16.hpp:12:31: fatal error: half_float/half.hpp: No such file or directory`

Any idea what this might be?

**Comment by soulslicer** [comment]
I just ran it with nv_caffe, and it runs about 25% slower

**Comment by gineshidalgo99** [comment]
Thanks a lot! I will check it in a couple weeks, I find myself in a super busy weeks but I will be back to this eventually!

**Comment by gineshidalgo99** [comment]
I will work in merging it this week/next week.

In the meantime, answering to: *Do you think it would be possible to test this automatically using Travis too?*
No, I can only test CPU version on Travis (it does not provide GPU support). The only way to test this would be if NVCaffe had some CPU-only version.

**Comment by peteruhrig** [comment]
I have written a step-by-step guide to install a portable container with NVCaffe and support for multiple NVidia cards as well as CPU. Maybe it helps someone here. http://peter-uhrig.de/openpose-with-nvcaffe-in-a-singularity-container-with-support-for-multiple-architectures/

**Comment by gineshidalgo99** [comment]
@peteruhrig Thanks! Your link will be pushed soon into the `Custom NVIDIA NVCaffe` section in the doc/installation.md!

**Comment by peteruhrig** [comment]
I'm still updating the page. It turns out NVCaffe does not support older cards. Officially they support only Pascal, Volta and Turing architectures. But Maxwell (GTX 980) works for me, too. Kepler cards (K40m) do not, however. Thus I'm building a third version for legacy GPU, i.e. is just the standard one with custom Caffe and GPU support.

**Comment by gineshidalgo99** [comment]
I am simply linking your URL, so as long as you do those edits on that URL, there will be no issue :)

Otherwise, simply post your final URL later and I'll update it.

**Pull request merged**
