### PR TITLE
Expose hand and face heatmaps

### PR DESCRIPTION
**Pull request by padeler**
Some small changes to the hand and face extractors.  Adding a getHeatmaps() method to their APIs similar to the getHeatmaps from the poseExtractor. 

Note: There is some code reuse in the extractors and they could all inherit common functionality from a base class. I did not want to mess with the organization of the library and add base classes for this pull request. However If you want to go that way I could help (and adapt my PR code to that format).

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Hi @padeler , I'd like to merge it. But I'd like first to change a few things to keep format and I want to link it better with body pose. Could you provisionally give me write access to your repo (I'd only modify the `expose_handface_heatmaps` branch or whatever branch you are using for this) so I can make those changes before pushing them to this repo? Thanks!

**Comment by padeler** [comment]
Hey @gineshidalgo99, no problem. I added you as a collaborator.

**Comment by gineshidalgo99** [comment]
Merged! Thank you for your big help!

Side notes:
- I changed quite a bit the structure and function names so I could follow the general OpenPose (OP) format.
- See tutorial_wrapper/1,2,3 to see how to access them from the OP output.
- I've also deleted myself from your repo so I cannot change anything else never again :)

Feel free to give me your feed-back or suggestions.

**Comment by padeler** [comment]
No problem, thank you for the great library!

**Pull request merged**
