### PR TITLE
Improve Python API including enabled AsynchronousOut mode

### PR DESCRIPTION
**Pull request by frankier**
Currently AsynchronousOut mode won't work with the Python API since it is not possible to get ahold of a Datum created inside OpenPose from the Python side. The reason for this is at the moment, lists are copied when going over the Python => C++ boundary. See https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html#making-opaque-types . To get the semantics of passing a mutable reference, we can wrap an STL type.

Unfortunately this is not quite sufficient. We need to pass a shared_pointer<vector<shared_pointer<datum>>> to `openpose::Wrapper`. The outer shared pointer is eventually pointed somewhere else in `queue.hpp`:

https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/3915b922eb345de9d788cb46541d42641aa014c4/include/openpose/thread/queue.hpp#L73

So we just swap that vector with ours, which should avoid copying the datum I think. I'm a bit confused about why there are so many levels of nesting though. A more idiomatic approach would be to just return a value in Python, but since the Python/C++ APIs are currently very similar, I thought I'd keep it this way and just adjust it to work in this case also. 

This PR also contains the following related changes:
 * Update Python tutorial for adjusted API and port C++ AsynchronousOut example to Python
 * Add ThreadManagerMode enum to Python interface

And a couple of unrelated bug fixes to the Python API:
 * Add `type_caster<op::Array<long long>>` so datum.poseIds can be accessed from Python
 * Cast empty Arrays on Datum to None in Python rather than numpy scalars of trash data.

### CODE REVIEW

**Comment by frankier** [comment]
Updated to only set up producer when we need synchronous input

**Comment by frankier** [comment]
Please review!

**Comment by frankier** [comment]
Please review!

**Comment by gineshidalgo99** [comment]
Sorry for the HUGE delay! I have finally reviewed it, there is a big question I have:

The new Python example you added (examples/tutorial_api_python/12_asynchronous_custom_output.py), how is it an asynchronous example? Where in that example you set it to be asynchronous?

**Comment by frankier** [comment]
You're right -- that seems to have been an oversight. Fixed.

**Comment by frankier** [comment]
Is there anything I can do to make this easier to review and merge?

**Comment by gineshidalgo99** [comment]
Pushed, this is an amazing PR, thanks a lot! (It just took me forever to review it given its complexity, sorry about that, but amazing PR!)

**Pull request merged**
