### PR TITLE
Add missing __init__.py to fix pycaffe import.

### PR DESCRIPTION
**Pull request by mkaraki48**
PyCaffe can't be found as a module in PYTHONPATH due to the misssing __init__.py file. I added it from caffe_rtpose.

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
I am sorry, I am not a big expert in Pycaffe, but shouldn't that file be automatically generated when compiling Caffe? Thanks!

**Comment by mkaraki48** [comment]
Compiling PyCaffe generates the _caffe.so and proto folder. The __init__.py has more to do with python than PyCaffe and is normally manually written for each module. A missing __init__.py results in failure to find module where an uncompiled PyCaffe results in failure to import module.
You can check the original structure of the python folder on the Caffe [master](https://github.com/BVLC/caffe/tree/master/python/caffe).

Cheers!

**Comment by gineshidalgo99** [comment]
Ok thanks! I realized now my error. It appears in the .gitignore file.

In order to give you the credit for the tip, do you mind do another commit here removing `*__init__.py` from the .gitignore file of the repo? Right after that I'll merge it.

Thanks!

**Comment by mkaraki48** [comment]
Cool. I'm glad it's solved.
You're welcome.

**Pull request merged**
