### PR TITLE
Python update

### PR DESCRIPTION
**Pull request by soulslicer**
This update adds hand and face to Python API

### CODE REVIEW

**Comment by itzku1** [comment]
Hi @soulslicer ,
Any progress with this commit?
Can I find somewhere flags.hpp?

Thanks!

**Comment by soulslicer** [comment]
Sorry, I have decided to revamp the entire python API by using Pybind11. This is so the entire OP functionality can become available in python. This probably won't be available till the end of the year.

You are however, welcome to use this commit for now

**Comment by itzku1** [comment]
@soulslicer , thanks for your reply!
I tried to rebuild everything with this commit but it does not work since the file flags.hpp is missing.
Any advice of using this code somehow?

Thanks

**Comment by akhalili** [comment]
Any update on this?

**Comment by gineshidalgo99** [comment]
Sorry for the delay and thanks for the PR. However, we have been working and will release very soon the new and a much powerful Python binding: #1014 , so this PR is no longer required or compatible for that version.

Note: If you find similar issues in the new implementation, go ahead to do a similar PR, that one would be accepted for sure. We really appreciate all the help we can get from the community. Best

**Pull request closed without merging**
