### PR TITLE
Speedup model

### PR DESCRIPTION
**Pull request by wangzhangup**
Modify 3-6 stage conv layers,  about 30% faster.

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Thank you very much!

I will merge it within 1-3 weeks! I am currently re-training your model as many iterations as our baseline, to see if I reduce the small accuracy drop even more! I'll keep this thread posted. Thanks!

**Comment by wangzhangup** [comment]
Did you try to use fp16?

**Comment by gineshidalgo99** [comment]
I am sorry, but I am not familiar with that term. Could you briefly explain what is fp16?

BTW: Re-trying your model status: in 300k iterations I only get 2% accuracy dropout with respect to our baseline (and obviously keeping the 30% speed up). With only 150k, it had a 30% accuracy drop. I am gonna keep it until 500k iterations to see if I even get better accuracy than our current baseline so it will be a considerably improved model.

**Comment by Tetsujinfr** [comment]
Fp16: floating point arithmetics on 16bits accuracy. It compares with fp32 or fp64 on GPU compilers.

Did you implement wangzhanup speedup version in the master branch?

**Comment by gineshidalgo99** [comment]
I left it at the bottom of my to-do list, the accuracy was lower so I wanted to play with it before adding it.

**Comment by costef** [comment]
Hi wangzhungup

I would try your version.
could you please explain what to do in order to run openpose with your model ?

**Comment by wangzhangup** [comment]
I had a model got 33 fps one 1080ti GPU.

**Comment by voronoipotato** [comment]
It would likely be valuable to see a fork of this project optimized for single person tracking.

**Comment by changjo** [comment]
@wangzhangup Hi. I was wondering how you trained the model using fp16.

**Comment by gineshidalgo99** [comment]
Hi all, I am closing this thread as the new OpenPose is approximately as fast as this model, while it includes 6 new keypoints and it also have about 10% more accuracy.

**Comment by Tetsujinfr** [comment]
Waow! You guys rock! Tx for the continous stream of improvements on OpenPose.

**Pull request closed without merging**
