### PR TITLE
Added new branch windows

### PR DESCRIPTION
**Pull request by helen-medina**
This branch contains the library Openpose for Visual Studio 2015.

### CODE REVIEW

**Comment by A7ocin** [comment]
Hey! When I try to compile the solution with VS2015 I get this error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "char caffe::gInstantiationGuardSGDSolver" (?gInstantiationGuardSGDSolver@caffe@@3DA)	Openpose	C:\openpose\project solution\Openpose\Openpose\bodyPartConnectorCaffe.obj	1	
`

I don't know how to deal with it, can you suggest a fix? Thanks

**Comment by orientalh** [comment]
Hi, helen-medina
Thank you to make Openpose window version.
I follow your tips
1. Visual Studio 2015
2. Required: CUDA, cuDNN must be already installed on your machine.
3. Build Caffe and other dependencies: caffe, opencv, openblas, boost will be installed in the folder 3rdparty with the script "buil_win.cmd". For more information, check the urls:

In number 3, i download Prebuilt binaries(Visual Studio 2015,CUDA 8.0, Python 2.7: Caffe Release) https://github.com/BVLC/caffe/tree/windows
And link the .dll and .lib files.

I also down load "libraries_v140_x64_py27_1.1.0" and link the address.

So i success build Openpose project and get Openpose.lib

Now i link Openpose.lib and build openposeDemo project. However i had error because of Openpose.lib.
image

**How solve this problem??**

Thank you and have a good day!

**Comment by helen-medina** [comment]
Hi A7ocin,
The issue seems to be related with the .sln and the symbols_headers.hpp. So, I have generated again the project solution. Please, rebase or clone the windows repository. 
Hopefully, it will fix the issue.

KIng regards,

Helen

**Comment by helen-medina** [comment]
Hi everyone,
 I have updated the repository because there was an issue with the project .sln. However, I would like to add that the "winddows branch" hans't been reviewed yet, so probably you could find some issues. But,  I am still working on it to fix these issues.

Regards,

Helen

**Comment by A7ocin** [comment]
Great! I'll test it and I'll let you know asap! Thanks!

**Comment by helen-medina** [comment]
Thank you too. Just remember it only release version it is available. Debug
mode has still some issue.

Regards.

**Comment by A7ocin** [comment]
Compiled everything in Release version.

========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

Still, I can't execute the generated executable file on windows under openpose\project solution\Openpose\x64\Release because it doesn't find the .lib libraries.

Even after copying all the required libraries directly into the executable's folder, the .exe crashes.
Can you suggest me a solution? Thank you, keep up the good work!

**Comment by helen-medina** [comment]
Hi,

The project doesn't have a rule post compilation for now, so you will need
to add the .dll manually. However, could you tell me which library is it
complain? Does it have any message error?

Thanks.

**Comment by A7ocin** [comment]
This is the list of all the missing dlls that should be added.
libs

And the first message error that I get after adding them and running the exe is:
`Exception thrown at 0x00007FF64A6A74B8 in OpenposeDemo.exe: 0xC0000005: Access violation reading location 0x0000000000000008.

If there is a handler for this exception, the program may be safely continued.`

In the C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtree file, line 1018 ( _Copy(_Right, _Copy_tag()); )

**Comment by helen-medina** [comment]
I had the same error not in release mode but in debug mode . In debug mode,
it generates an exception for the function std::copy and I am not sure how
to fix that. However, in release mode it works fine. But, I will double
check it.

Thank you.

**Comment by A7ocin** [comment]
Actually, it is giving me that error with release mode, x64. Should I build a x86 version instead? Thanks.

**Comment by helen-medina** [comment]
It is not necessary, it should work for x64. I cn't check it rigth now, but
I will check tomorrow if I have the same issue in another machine.

Just one question. Did you run the script build_win.cmd to build caffe?

**Comment by A7ocin** [comment]
Yes, I did and it build everything with no errors but with 1336 warnings of the kind:

"conversion from 'uint64_t' to 'int', possible loss of data"

**Comment by A7ocin** [comment]
Yes, I did. It did build everything with no errors but 1k+ warnings of type conversion (possible loss of data)

**Comment by orientalh** [comment]
Hi, helen-medina 
Thank you, I success to build Openpose and OpenposeDemo.

However i compile and run i had a access violation error. 
image

I saw you recommend this error to AntonN11 and
I change "char" -> "int" BUT i don't understand "the "POSE_COCO_BODY_PARTS" and "POSE_MPI_BODY_PARTS" variables are empty". 

Window version is only run on release mode so i could not use debug mode.
How do i solve this problem??
Please give me detailed tips....

**Comment by A7ocin** [comment]
It's giving me the same error...or at least I think so, since it's in korean :-P 
It seems like a memory allocation problem, due to pointers

**Comment by orientalh** [comment]
Hi, A7ocin

I also guess this error occur because of memory allocation.
But it is release mode, so i could not do debug and i do not know which pointer is promblem

**Comment by hemecha** [comment]
Hi, 
I have been able to debug and the error is raised for this line:
static const std::array<std::map<unsigned char, std::string>, 3>   POSE_BODY_PART_MAPPING{ POSE_COCO_BODY_PARTS, POSE_MPI_BODY_PARTS, POSE_MPI_BODY_PARTS };

imagen

The error is because of  dynamic initializer, but I don´t why it happens, and I am not sure if it related to threads. 
More people have the same issue:
https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/17#issuecomment-303057004

**Comment by A7ocin** [comment]
Thank you. I'll test it later and see if I manage to solve something

**Comment by A7ocin** [comment]
Meanwhile can you tell me how you managed to debug it so I can do it myself? Thanks

**Comment by A7ocin** [comment]
I tried to figure something out. Can you tell if the error is related with a raw pointer? Because that kind of error usually happens when you don't assign the raw pointer to a shared pointer as soon as it is created or if you delete if when it is still used by the shared_ptr.

**Comment by helen-medina** [comment]
Hi,

To debug the system, you will need to follow these steps:

- Build caffe in debug mode. You can open the solution caffe.sln created, change the option from release to debug in the control panel and build it to generate the library caffe-d.lib y proto-d.lib

- In the openpose project you need to configure the project properties to include the header files, link to the libraries: caffe, boost, opencv for debug mode, and finally add the flags for the preprocessor. You can just copy from the project properties for release mode.
- Debug the project.

I hope it helps.
Regards.

**Comment by helen-medina** [comment]
Hi,

The user AntonN11 has solved the issue. You can find below the solution. However, it doesn´t explain why initializer fails.
https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/17#issuecomment-303057004

If you find the thread  issue, you will find the solution there as well. 
When I can I will update the repo with these solution unless someone knows a better solution.

Thank you AntonN11 for your help.

**Comment by orientalh** [comment]
Thank you AntonN11 and helen-medina 

I solve empty variable error because of yours!

However i had another error.
image

I search error about ucrtbase.dll, however i do not know why it happens...

If do you have this error and solve. Please teach me!

One more time thanks very much!!

**Comment by orientalh** [comment]
Hi, 
I continue to run Openpose.
When i run the openpose.cpp, I had this error (**errorMessageToPropagate	"\nError:\nVideoCapture (video) could not be opened for path: 'examples/media/video.avi'.\n\nComing from:\n- ..\\..\\..\\src\\openpose\\producer\\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader(...	std::basic_string<char,std::char_traits<char>,std::allocator<char> >**)

I guess this error is occurred because of path. I write code like this
image

Is this way is wrong?? or should i write more path on other line??

How should i run on video mode??

**Comment by helen-medina** [comment]
Hi,

You need to run the full path for the video and the model folder, otherwise it could have some problems to opened. Also, check if you have your application linked to the opencv library:
opencv_videoio310

**Comment by orientalh** [comment]
Hi, helen-medina 
Thanks to reply. But i still have same error.

I linked  to the opencv library: opencv_videoio310.
and i try to run image. but it also have error(	**errorMessageToPropagate	"\nError:\nFolder examplesmediaCOCO_val2014_000000000328.jpg does not exist.\n\nComing from:\n- ..\\..\\..\\src\\openpose\\utilities\\fileSystem.cpp:op::getFilesOnDirectory():157\n- ..\\..\\..\\src\\openpose\\utilities...	std::basic_string<char,std::char_traits<char>,std::allocator<char> >**
)

My code is
**DEFINE_string(image_dir,                "examples\media\COCO_val2014_000000000328.jpg",             "Process a directory of images. Use `examples/media/` for our default example folder with 20 images.");**

I also try to use full path such as
DEFINE_string(image_dir,                "C:\Users\han\Desktop\openpose-windows\openpose-windows\examples\media\COCO_val2014_000000000328.jpg",             "Process a directory of images. Use `examples/media/` for our default example folder with 20 images.");

But it could not run because of format.....

What is the full path??

**Comment by helen-medina** [comment]
The error means visual studio can´t find the image:
nError:\nFolder examplesmediaCOCO_val2014_000000000328.jpg does not exist

You need to use the other backslash "/" or "\\", you have to do this in windows. Try 

C:/Users/han/Desktop/openpose-windows/openpose windows/examples/media/COCO_val2014_000000000328.jpg

If it doesn´t work try to copy the image in simple path, this one is little large, but use / or "\\".

**Comment by orientalh** [comment]
Hi helen-medina

I solve the problem to write it
(**C:\\Users\\han\\Desktop\\openpose-windows\\openpose-windows\\examples\\media\\**)
Not write image file name.

But i had another problem like this
image


My model folder path is like this
image

image

image

image

How can i solve this cudaSuccess <2 vs. 0> out of memory error???

**Comment by helen-medina** [comment]
Not sure, I haven´t had that error before, there was an issue with threads, (threadManager.hpp) the fix was released in this foro by AntonN11. If it is already fix, I suggest to debug and find out which was is raising that error.

Sorry I can´t help more.

**Comment by gineshidalgo99** [comment]
@orientalh you are not using cuDNN, the documentation is clear about the need of cuDNN....

**Comment by orientalh** [comment]
Hi helen-medina

I success to use Openpose on window.
image

Actually it can not run..... So i just make OpenposeDemo.exe and move it another computer.
That computer run this exe file, but it can not compile i guess the problem is SDK version problem....

I have two problems.

1. The frame speed is so slow, so the video is running very slow.

2. Webcam display not good like this
image

The screen color is red and It can not detect and track person.

Thank you i can do here for you^^
And i hope the two problems are solved soon.

**Comment by helen-medina** [comment]
The speed could be slow, it depends from you card graphic. You can check in the link below the speed for your card graphic:
https://docs.google.com/spreadsheets/d/1-DynFGvoScvfWDA1P4jDInCkbD4lg0IKOYbXgEq0sK0/edit#gid=0
About the webcam no idea. Maybe it is something related with drivers, but don´t know. In my machine works fine.

Regards.

**Comment by gineshidalgo99** [comment]
I sent several fixes to Helen (e.g. fixing the segmentation error from the std::map when initializing). Please, re-build the whole project after Helen adds my new changes on this pull request. Thanks!

**Comment by A7ocin** [comment]
@orientalh how did you solve the ucrtbase.dll error?

**Comment by orientalh** [comment]
Actually i also do not run on window 10. So i try it another computer on window7 which is build well. Then i copy and change ucrtbase.dll file in system32 folder. Finally i can build Openpose on window10.
You should change ucrtbase.dll file!!

**Comment by A7ocin** [comment]
Ok, now everything seems to run fine on windows too, also from Visual Studio. Did you include the 30% performance increase suggestion yet? Meanwhile, I'll try to find a configuration to make everything faster, thank you!

**Comment by gineshidalgo99** [comment]
No 30% speed up yet. I will clearly specify both Windows and 30% speed up on the README first lines when I add them so people can actually realize.

**Comment by AntonN11** [comment]
To open and read a video, I had to add the opencv_ffmpeg310_64.dll. I also added the following code : 
image

**Comment by gineshidalgo99** [comment]
@AntonN11, why did you have to change the braces by parenthesis? Which error or why is it not working otherwise? Thanks!

**Comment by AntonN11** [comment]
@gineshidalgo99, I did this change and added the missing dll as well when I had issues testing a video input. I just removed my code change and it works flawlessly. I am sorry for the confusion. The code I pictured in my last post is not necessary. The reason I couldn't open the video (.avi) was because of the missing dll.

**Comment by AntonN11** [comment]
I did the following 
 - adjusted the "net resolution" to 320x176
 - used 2xGTX 980 (my 650w power supply is not happy) 
 - small resolution gray scale video (752x480) with around 15 people in it
 - used the "MPI_4_layers" model
 - display a resolution of 1280x720
 - used the additional option of compute_50 and sm_50 for my particular GPU
image
And in the end, OpenPose got up to 32fps. To me, this is really good. I'll see if I can find 2 x GTX1080Ti or better cards ⚡️

**Comment by gineshidalgo99** [comment]
@AntonN11 Thank you for the feedback!
About the 50 architecture, it is specified in the `Code generation` section:
https://stackoverflow.com/questions/14411435/how-to-set-cuda-compiler-flags-in-visual-studio-2010

**Comment by AntonN11** [comment]
Yes I fully agree with you. The thing is, I got tired of the compilation warnings : 

image

I figured that adding 
_-gencode=arch=compute_50,code=\"sm_50,compute_50\" fixed those warnings.

**Comment by gineshidalgo99** [comment]
@AntonN11 True! Thanks! I just cleaned all warnings (up to level 4) inside OpenPose (but obviously I could not get rid of the Caffe/OpenCV ones). I will be doing a final merge soon (I hope between today and Sunday)

**Comment by orientalh** [comment]
Hi,

I have a question about output format.
I want to get coordinate with each joint. 

For example i want to have head and right hand. However  **"POSE_COCO_BODY_PARTS" and "POSE_MPI_BODY_PARTS" do not have a variable about hand**. How i get hand varable??

To get joint coordinate, couid i use 'rapperStructOutput.hpp'and 'fileStream.hpp'??
**How can i get coordinate on realtime?** Which function is useful for it??

**Comment by gineshidalgo99** [comment]
I could not directly merge it for the conflicting files (I am still not an expert on GitHub), but I manually added it with a few extra changes (cleaned warnings + installation/compilation instructions). Thank you for all your feed-back to make it possible! Specially to @helen-medina !

**Comment by raymondsa** [comment]
openpose
I am  not able to compile the code to get Openpose.lib, any help please ?
I follow  the user  'orientalh' steps:

   1)   Visual Studio 2015
   2) Required: CUDA, cuDNN must be already installed on my machine.
  3) I download Prebuilt binaries(Visual Studio 2015,CUDA 8.0, Python 2.7: Caffe Release) https://github.com/BVLC/caffe/tree/windows
And link the .dll and .lib files.

I also downloaded  "libraries_v140_x64_py27_1.1.0" and link the address.
https://github.com/willyd/caffe-builder/releases

**Comment by gineshidalgo99** [comment]
@raymondsa Please use the official installation steps:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows

If you still have problems after following the official steps, then open a new issue please. Thanks!

**Comment by gineshidalgo99** [comment]
@raymondsa Please, use the official steps. This branch was merged and updated.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows

If you still have problems after following these steps, open a new issue please. Thanks!

**Comment by AntonN11** [comment]
Hello, FYI : I had 2 issues running OpenPose in Debug mode (with a webcam or images or a video).

1) It seems there is an assertion error in openCv.cpp, line 47 : 

image

The ".at" method crashes at its last assertion call here : 

image

The "elemSize()" is 3 and "CV_ELEM_SIZE(DataType<_Tp>::type)" is 1. I can't figure out why. I even tried to create a similar cv::Mat and fill it with whatever value, and it had the same assertion error.
I got passed this problem in openCV.cpp using the line you see in my first picture in this post (.data[...]). 

2nd issue was in fileSystem.cpp line 60, when writing a "json" pose data file : 

image

To make it work, I added line 61.

Thanks,

Anthony

**Comment by helen-medina** [comment]
Hi,

About the second issue, the feature "cend" is supported by visual studio 2015 (see link below), so it shouldn´t fail, however it seems to be an issue with windows.

https://msdn.microsoft.com/en-us/library/syxtdd4f.aspx
For the another issue, I am afraid I can´t help, I haven´t get it too far as you have yet. Let´s see if Ginés can help.

Regards.

**Comment by AntonN11** [comment]
Alright, thank you for your reply.

**Comment by gyc990326** [comment]
Well maybe the first issue is because the developer want to use the mat as an one-dimention array, but opencv refuses to do so. We can use the ptr(y) instead. I changed the loop into the following code

            for (auto c = 0; c < resolutionChannels; c++)
            {
                const auto offsetChannelC = c*offsetBetweenChannels;
                for (auto y = 0; y < resolutionSize.height; y++)
                {
					uchar *ptr = cvMat.ptr<uchar>(y);
                    const auto cvMatOffsetY = y*resolutionSize.width;
                    const auto floatImageOffsetY = offsetChannelC + y*resolutionSize.width;
                    for (auto x = 0; x < resolutionSize.width; x++)
                    {
                        const auto value = uchar(   fastTruncate(intRound(floatImage[floatImageOffsetY + x]), 0, 255)   );
						//ptr = cvMat.ptr<uchar>(resolutionChannels*(cvMatOffsetY + x) + c)
						*(ptr + x*resolutionChannels + c) = value;
                    }
                }
            }

and it works. :)

**Comment by gyc990326** [comment]
The second issue can be solved by changing 
    if (*directoryPath.cend() != '/')
to
    *(directoryPath.cend()-1) != '/')
which means get the last character of the string.

**Comment by gyc990326** [comment]
Reference:
https://stackoverflow.com/questions/39778207/converting-caffe-caffedatum-to-opencv-cvmat-in-c
https://stackoverflow.com/a/4885533

**Comment by aues** [comment]
Hi, Helen-medina! 
I succesfull builded debug version of the openpose.lib and OpenPoseDemo.exe with CUDA support (GPU mode), but I don't need GPU, I need CPU only mode. How make windows_project for Visual Studio 2015 with CPU_ONLY without CUDA support. Please help!

**Comment by gineshidalgo99** [comment]
There is no CPU_ONLY version. CUDA (i.e. NVIDIA) is required, as the hardware requirements specifies in the documentation

**Pull request closed without merging**
