### PR TITLE
Integrate windows branch into master branch and several improvement

### PR DESCRIPTION
**Pull request by gyc990326**
1. I changed the caffe-windows path to 3rdparty/caffe-windows/caffe-windows in order to avoid conflict with the linux version of caffe, our changes are applied to the submodules when we execute the install script (see the 3rdparty/patch)
2. I changed the caffe into submodules so that it would be fast and easy to catch up with the newest version.
3. Debug version in windows works now (if my last pull request was merged), by modifying the build script of caffe and the linker input
4. In windows we needn't to manually execute the build_win.cmd for caffe. It will be automatically executed as an Prebuild Event.(see 3rdparty/install_caffe.cmd)
5. A small bug in faceExtractor is fixed in order to run the Debug version
6. The change of master branch has been merged. The face part works well on windows.

If we merge the master and windows branch together, it will be a lot easier to maintain the repo.

### CODE REVIEW

**Comment by gyc990326** [comment]
Well I forgetted that I haven't tried to the Linux version now since I does not have a Linux machine with CUDA, but it should be able to work.

**Comment by gineshidalgo99** [comment]
Hi, I'd like to check your version, but there are way too many files updated (GitHub says `687 files changed` given that all caffe files were removed when replaced for the submodule), so it is really hard for me to debug your pull request. Could I know which one of your 6 points is actually still pending w.r.t. the current Windows version? E.g. face was add and the debug version is working now. Thanks!

**Comment by gyc990326** [comment]
The small bug in point 5 is fixed by yourself after my PR. In fact I'm not expecting this branch to be merged, since github will merge the branch and mess up the repo. Since the universal CMake script is on your todo list, we can simply wait for the PR #87 gettint ready.
If you really want to use this integrated branch, I suggest you change the repo according to the following step:
1.deleting all caffe folder and then initialize the git submodule caffe and caffe-windows using the path specified above.
2.copy the added file in the 3rdparty folder(scripts and patches)
3.copy all files in windows_project.
The features above are all implemented and finished. 
We does not need to change the library or demo's code for the windows version, however we have to add the file newly created to the project or it won't be compiled. I've been doing this for a long time as the windows branch are lagged behind for a long time.:)

**Comment by gineshidalgo99** [comment]
OK thank you for the suggestions. I'll like to join Windows-Ubuntu at some point. So I'll definitively check this then. Best

**Comment by gyc990326** [comment]
Thanks. Please tell me if you need help or have any questions.:) Have a nice day.

**Comment by gineshidalgo99** [comment]
I've just added a commit that merges Ubuntu and Windows versions. In addition, the Windows version should be easier to install (no need to install Caffe).

The only point I did not do that you did was the caffe submodule

**Comment by gineshidalgo99** [comment]
@gyc990326 And hands has also been added to the new easier-to-install Windows version! I changed the old windows branch to `deprectated_old_branch`. And everything will work from now on with the new merged version (thank you for your help!).

I'll close this pull request since it's from the old branch.

Please, feel free to make a new pull request to the merged version with any change that you did on this pull request and I did not add to the new merged version. Thanks!

**Pull request closed without merging**
