### PR TITLE
Jetson TX2 JetPack 3.1 install scripts

### PR DESCRIPTION
**Pull request by bushibushi**
Use : ./ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.1.sh

Jetson TX2 with JetPack 3.1 install scripts, I advise to use the following parameters with the demo :
- external webcam
- camera_resolution 640x480
- net_resolution 128x96
- face_net_resolution or hand_net_resolution 256x256

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Hi, thank you for the pull request!!! Could you please add the instructions to install it in a new *.md file called `doc/installation_jetson_tx2.md` (including your 1st comment on this thread), so I can directly link it to the current installation doc? Thank you again!

**Comment by gineshidalgo99** [comment]
Thank you very much! I'll merge within 1 week!

**Comment by bushibushi** [comment]
Hi, you're welcome ! Thanks for this very nice tech demo !

Doc is done.

**Comment by bushibushi** [comment]
By the way I intend to look into Tensor RT for optimising performances on TX2, any tips on where to start changing code ?

**Comment by gineshidalgo99** [comment]
Unfortunately I have no experience in Tensor RT yet, I'd like to learn it too but I have a long to-do list first  :disappointed:

**Comment by ouceduxzk** [comment]
@bushibushi  I don't think tensorrt will help since what tensorrt does is using int8 instead of fp32 which loss too much information to correctly identify the exact location of pose. I tried with mobilenet as a backbone, but it does not work neither

**Comment by nsfw** [comment]
@bushibushi -- First thanks for all the work. It really helped me get started quickly.

I'm finding that performance on TX2 is on the very low end of the scale of 
[OpenPose Benchmarks](https://docs.google.com/spreadsheets/d/1-DynFGvoScvfWDA1P4jDInCkbD4lg0IKOYbXgEq0sK0/edit#gid=0), somewhere in the 0.5fps to 1fps when using the network sizes there. 

Is this consistent with your experience?

I find I can get around 3fps  --net_resolution 320x160 --resolution 640x360 with reasonable results.

**Comment by bushibushi** [comment]
@nsfw Glad to help !

As indicated [in the documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2.md) I had to go down to very low resolution to get more acceptable FPS (parameters in the doc). Be certain to use alos the jetson_clocks.sh script to enable full performance.

**Comment by vusdo** [comment]
@bushibushi 

I received a TensorRT Demo from your repo.
We expect performance to improve with TensorRT.

How many FPS do you get when you run ./pose.sh?

I run the pose, resulting in 8.7 fps.

3_extract_from_image_TensorRT.bin Test result is 13676.226541ms.


Is this the TensorRT optimization result?

**Comment by bushibushi** [comment]
Hi, I did not think to have sent anything as it is still WIP.

Currently I have inference running but the data does not flow well and the inference does not seem to be running on something correct. 

With TensorRT the network conversion and tuning takes some time (approx 12 sec) but then the inference is 4 to 8 times faster seemingly (we'll see when it runs on the correct data). I've added the correct timings in examples/tutorial_pose/1_.... and 3_... on which I am debugging these improvements. I'll port it to the live demo afterwards so no it's not the final TensorRT optimization result.

> 3_extract_from_image_TensorRT.bin Test result is 13676.226541ms.
This is mostly setup time. The inference is much quicker than that (hundreds of ms vs > 2s for this image and net size).

**Comment by bushibushi** [comment]
So the 8.7 FPS are only due to reduction in net size from original openpose code in caffe.

**Comment by bushibushi** [comment]
@vusdo by the way if you have any advice for the data layout (I am trying to pass the float* data from tensorRT to the rest of the workflow in caffe, quite a headache!), I would be glad to hear it !

**Comment by bushibushi** [comment]
@vusdo Here you go, 3_extract_from_image_TensorRT.bin is now correctly infering pose (and only pose) with TensorRT and gaining *2 inference time. 

A lot of cleaning remains before I port it to the demo, check again in a few hours or tomorrow.

**Comment by vusdo** [comment]
@bushibushi 

I want to learn TensorRT but it is difficult to get started.

I respect your efforts and I will always support you.

Great developer.

**Comment by vusdo** [comment]
`3_extract_from_image_TensorRT.bin: caffeParser.cpp:94: virtual nvinfer1::DimsHW CaffeParserPoolingDimsCallback::compute(nvinfer1::DimsHW, nvinfer1::DimsHW, nvinfer1::DimsHW, nvinfer1::DimsHW, const char*): Assertion 'input.h() + 2 * padding.h() >= kernel.h()' failed.`

**Comment by bushibushi** [comment]
Yeah I did not put up a tutorial yet, I did not find a way to modify this at runtime : the caffe proto from opencv have 1x1 for input size (and it is modified at runtime). But for TensorRT conversion you have to modify the caffeProto and put the desired width and height (warning it's height then width).

**Comment by megashigger** [comment]
@bushibushi do you know why performance is so low compared to other graphics card when using the same net_resolution? i'm getting 1.5 fps for body only but would've expected much more with the tx2 specs..

**Comment by bushibushi** [comment]
@megashigger well,

1) there's only 256 cuda core on the tx2, most GPUs have at least 4x that now... the titan X Pascal 2016 has 14 times more. I think shared RAM/VRAM has both upsides (no overcost for GPU computation as free HostMemToGPU copies) and maybe downsides for memory access speed ? 

2) This demo is quite resource consuming, thankfully as I said it supports downsizing the main net very well and you can get 8.7 fps with w128xh96 net and jetson_clocks activated.

I optimised many things in the demo including making the main net inference run in TensorRT (2x faster than caffe), but I did not to pass much further than 10 FPS. I have weird timings for the GPU computations that I need to clarify.

**Comment by gineshidalgo99** [comment]
Hi @bushibushi , would you be willing to share your TensorRT implementation? (e.g. through pull request or by email to gineshidalgo99@gmail.com)? I'd like to test the accuracy reduction and depending on how much it decreases, directly integrate it with OpenPose if you are willing to share it. Thanks!

**Comment by bushibushi** [comment]
Sure, I was working on a PR last week but got caught up in other work duties. Got stuck with precompiler guards / templates issues for splitting builds with and without TensorRT. I can share the PR sooner for you to test it, though, but not everything is cleaned / automatised : didn't find a way to change caffe prototxt file at runtime (TensorRT conversion tools don't support 1x1 input in the prototxt).

**Comment by gineshidalgo99** [comment]
@bushibushi My idea was to first analyze the accuracy hit (w.r.t. original Caffe net), so I do not mind how dirty it currently is.

So it is up to you when you think it is ready to be shared, but I am OK with either you making the pull request now (and just indicate it is still unfinished) or after it is cleaned, or maybe share it with me so I can take the look to the accuracy. It is your work, so this is up to you :)

**Comment by megashigger** [comment]
@bushibushi thanks for explaining. do you have any suggestions for improving performance on an embedded devices (wired camera). using multiple tx2's, using another embedded chip, etc.? thx!

**Comment by bushibushi** [comment]
@megashigger Have you tried the -net_resolution 128x96 yet ? After that you can try my PR with Tensor RT, you can get to reasonable FPS. Just wait for it to be finished if you want it to work out of the box.

**Comment by megashigger** [comment]
@bushibushi yes i've lowered the net_resolution to that but ideally but am getting an accuracy loss that's too high.. thanks for the work on TensorRT! What's the impact on FPS from that alone? thank you.

**Comment by bushibushi** [comment]
@megashigger Most of the time I get a 50% speedup (*1.5) up to a point where net inference isn't the limiting factor.

**Comment by megashigger** [comment]
@bushibushi thanks so much. were you able to get it working with the onboard camera? I can get a video stream going with the command below, but am not sure how to hook it up with openpose.

`gst-launch-1.0 nvcamerasrc ! 'video/x-raw(memory:NVMM), width=640, height=480, framerate=30/1, format=NV12' ! nvvidconv flip-method=2 ! nvegltransform ! nveglglessink -e`

**Comment by ildoonet** [comment]
This is merged, but I re-implemented in tensorflow to speed-up using mobilenet's depth separable convolution.

https://github.com/ildoonet/tf-openpose

**Comment by Rafcin** [comment]
This should be updated to use Caffe 2 and Jetpack 3.2

**Pull request merged**
