### PR TITLE
support IP camera protocol like RSTP

### PR DESCRIPTION
**Pull request by awanabe**
* Change the type of Argument `Camera`.
* Add ProducerType to VideoCaptureReader init

CMD FOR IP CAMERA (HAIKANG)
```
./build/examples/openpose/openpose.bin --camera 
 'rtsp://[USERNAME]:[PASSWORD]@[IP]:[PORT]/h264/ch1/main/av_stream'
```

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Just curious, if it behaves like a normal video, does the following work to open it?
```
./build/examples/openpose/openpose.bin --video 
 'rtsp://[USERNAME]:[PASSWORD]@[IP]:[PORT]/h264/ch1/main/av_stream'
```

**Comment by awanabe** [comment]
It can be executed, But quit quickly, due to the logic of Video Input will check the path of video.
RTSP protocol is not the format a system path.

**Comment by sberryman** [comment]
I can also confirm that the current master branch will open the video stream (RTSP) and process the first frame then exit.

**Comment by GeorgianaPetria** [comment]
Is it possible to use this change in order to process an ip camera video stream?

**Comment by Jamboalv** [comment]
Recently, I need do some experiments on ip camera , this kind of changes help me a lot !!!  Thanks a million~
Ubuntu16.04 /cuda8/ 2 Geforce GTX 1080 cards / IP CAMERA (DAHUA) @awanabe

**Comment by gineshidalgo99** [comment]
IP camera support has been officially added. Let me know whether it works fine. Thanks!

(I could not directly merge the repo given all the merging errors, so I simply re-implement it)

**Comment by Jamboalv** [comment]
I have tried it just now, it works very well !
./build/examples/openpose/openpose.bin --ip_camera "ip camera address"

**Comment by Jamboalv** [comment]
I am sorry to tell the truth that if I use ip_camera , json file couldn't be opened. However, other things are OK!

**Comment by gineshidalgo99** [comment]
@Jamboalv Sorry, fixed now. Let me know any other issue

**Comment by aniketzz** [comment]
can i use my cell phone as ip camera. I have been trying to use my cell phone camera as a ip camera but i am getting some errors. i am able to access the phone as ip camera from my browser but when i am trying to run it on the code i couldn't.

**Comment by gineshidalgo99** [comment]
I was previously that error, it's because it requires something like .mpg or something similar at the end of the URL (at least for OpenCV, google the error for OpenCV). We simply wraps OpenCV IP support, so if you make it work with a simple OpenCV webcam demo, it should work in OpenPose.

**Pull request closed without merging**
