### PR TITLE
Added Dockerfile and instructions for creating Docker image

### PR DESCRIPTION
**Pull request by tlkh**
Hi everyone, I am a very inexperienced contributor so criticism is welcome. I noticed #12 but the status of that seems a little uncertain. Hence, I decided to give this a shot.

I'm proposing that we create a Dockerfile that will tackle OpenPose + Python bindings + GPU acceleration (CUDA), since this is a common configuration yet is more tricky to get right.

Here are the changes made in the commit:

* Added Dockerfile
* Building OpenPose with the Python bindings (something the other proposed Docker image lacks)
* Added folder for support files for building the Docker image
* Instructions outlined in a README in said folder
* A command + script that tests the import to ensure that it is working in the container.

I believe this is helpful, but if my contribution standard is not up to bar please do give any feedback or advice.

Thank you and have a nice day!

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Thanks! I won't be able to review it in the short run, but it is a welcome PR and I will eventually check it!

**Comment by esemeniuc** [comment]
I've made a much simpler image with a newer version of CUDA here: https://github.com/esemeniuc/openpose-docker
Its working with the python interface as well

**Comment by gineshidalgo99** [comment]
I will close this, but I have added a link to both of your Docker files in our doc/installation.md (will be pushed in the next commit), together with the many other Docker files people shared. Thanks for the help!

And feel free to post newer Dockerfiles in here, I will keep adding them to that file :)

**Comment by neonb88** [comment]
As of `Wed Sep  4 04:41:10 UTC 2019`, @esemeniuc 's docker implementation is giving me the error 
```
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
./build/examples/openpose/openpose.bin: symbol lookup error: /openpose/build/src/openpose/libopenpose.so.1.4.0: undefined symbol: _ZN5caffe3NetIfE21CopyTrainedLayersFromERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I believe this is an issue with `Ubuntu 18.04` due to the comment [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1181), but I'm not 100% sure.  If anyone tries his docker image and manages to fix the issue, please let me know.

Cheers,
Nathan

**Comment by kjacks21** [comment]
@neonb88 what did you run to cause the issue? I used the `cwaffles/openpose-python` image via the following command listed on the Docker page 

`docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 cwaffles/openpose-python`

And was able to run the openpose demo without displaying a video (necessary or else you'll get an `Unable to init server: Could not connect: Connection refused` error).

**Pull request closed without merging**
