### PR TITLE
CMake build system

### PR DESCRIPTION
**Pull request by chriamue**
Hi I built some cmake files based on this template: https://github.com/cginternals/cmake-init
It's not perfect but maybe you will copy it into a new branch for testing.
I will still work on it the next days.

Building with CPU_ONLY is not supportet and windows build is not tested yet.
Travis build is supported as you can see here: https://travis-ci.org/chriamue/openpose
Dockerfile is also included and builds: https://hub.docker.com/r/chriamue/openpose/
The Dockerfiles are inspired by this pull request: https://github.com/CMU-Perceptual-Computing-Lab/openpose/pull/12

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Hi. Thank you! Let me know when you think you are done with it and we will check it (not soon because we are with hands and other issues in the meanwhile). Thanks!

**Comment by chriamue** [comment]
I'm testing the cmake here: https://github.com/chriamue/dressup.
I will check to export the used libraries in the cmake version.
Then it will be possible to use
find_package( openpose COMPONENTS wrapper REQUIRED )
without
find_package( Caffe REQUIRED ) .

**Comment by chriamue** [comment]
When compiling with CPU_ONLY I get some linker errors.
The *.cu files are not compiled then. Maybe we have to change some parts in the code and add some
 `#ifndef CPU_ONLY ...
#endif`

`[ 83%] Linking CXX executable ../openpose
../libcore.so.1.0.0: undefined reference to `void op::nmsGpu<float>(float*, int*, float const*, float, std::array<int, 4ul> const&, std::array<int, 4ul> const&)'
../libcore.so.1.0.0: undefined reference to `void op::maximumGpu<double>(double*, double const*, std::array<int, 4ul> const&, std::array<int, 4ul> const&)'
../libcore.so.1.0.0: undefined reference to `void op::resizeAndMergeGpu<float>(float*, float const*, std::array<int, 4ul> const&,std::array<int, 4ul> const&, std::vector<float, std::allocator<float> > const&)'
../libcore.so.1.0.0: undefined reference to `void op::resizeAndMergeGpu<double>(double*, double const*, std::array<int, 4ul> const&, std::array<int, 4ul> const&, std::vector<double, std::allocator<double> > const&)'
../libcore.so.1.0.0: undefined reference to `void op::nmsGpu<double>(double*, int*, double const*, double, std::array<int, 4ul> const&, std::array<int, 4ul> const&)'
../libpose.so.1.0.0: undefined reference to `void op::connectBodyPartsGpu<float>(op::Array<float>&, float*, float const*, float const*, op::PoseModel, op::Point<int> const&, int, int, float, int, float, float)'
../libpose.so.1.0.0: undefined reference to `void op::connectBodyPartsGpu<double>(op::Array<double>&, double*, double const*, double const*, op::PoseModel, op::Point<int> const&, int, int, double, int, double, double)'
../libcore.so.1.0.0: undefined reference to `void op::maximumGpu<float>(float*, float const*, std::array<int, 4ul> const&, std::array<int, 4ul> const&)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/openpose.dir/build.make:173: recipe for target 'openpose' failed
make[2]: *** [openpose] Error 1
CMakeFiles/Makefile2:1970: recipe for target 'examples/CMakeFiles/openpose.dir/all' failed
make[1]: *** [examples/CMakeFiles/openpose.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by chriamue** [comment]
Here you can see how openpose is built with cmake. A deb package is created and installed,
then an example program is built using cmake and linking to openpose.
https://hub.docker.com/r/chriamue/dressup/builds/bp3ctot8bcax8q9jmixoaj3/

**Comment by gineshidalgo99** [comment]
Hi, given that we had 2 different CMake, we decided to use the other one because it's quite specific and more clear to read in the future for someone maintaining it. But please, feel free to add from your CMake any extension (e.g. Windows version) that we do not have at the moment.

**Pull request closed without merging**
