### PR TITLE
Add AppVeyor support

### PR DESCRIPTION
**Pull request by thomasfaingnaert**
I added AppVeyor configuration to build OpenPose automatically on Windows (CPU version).
A ZIP with the build artifacts is also available (e.g. https://ci.appveyor.com/api/buildjobs/na0fs1ws5sdgke3q/artifacts/openpose.zip)

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Thanks! I'll check it!

**Comment by gineshidalgo99** [comment]
I am not familiar with it, so could you share some additional instructions on how to make this work? I.e., after I accept the PR, what else is required for it to work? Thanks!

**Comment by thomasfaingnaert** [comment]
You need to add AppVeyor as a GitHub app to this repo as well.
I believe if you go to https://www.appveyor.com and log in using your GitHub account, it should automatically walk you through the setup process.
Once AppVeyor is registered, Windows builds should work automatically.
From the build description (e.g. https://ci.appveyor.com/project/thomasfaingnaert/openpose/builds/23122680), you can see the log and the generated build artifacts.
You may also want to add a status badge to the README (see https://www.appveyor.com/docs/status-badges/).
Let me know if I can help with anything else.

**Comment by gineshidalgo99** [comment]
Added, configured, and build icon in the README, thanks a lot!!!

**Pull request merged**
